# Generated by Django 4.1.6 on 2023-03-23 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_names', models.CharField(max_length=20)),
                ('profile_pics', models.ImageField(default='', upload_to='pics')),
                ('phone_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('gendre', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('state_of_origin', models.CharField(max_length=20)),
                ('lga_origin', models.CharField(max_length=100)),
                ('scheme_name', models.CharField(max_length=100)),
                ('year_of_application', models.CharField(max_length=4)),
                ('residencial_address', models.CharField(max_length=100)),
                ('state_of_residence', models.CharField(max_length=20)),
                ('lga_residence', models.CharField(max_length=100)),
                ('highest_level_of_education', models.CharField(choices=[('NURSERY', 'NURSERY'), ('PRIMARY', 'PRIMARY'), ('SECONDARY', 'SECONDARY'), ('DEGREE', 'DEGREE'), ('MASTERS', 'MASTERS'), ('PHD', 'PHD')], max_length=20)),
                ('id_type', models.CharField(choices=[('NATIONAL IDENTITY CARD', 'NATIONAL IDENTITY CARD'), ('VOTERS CARD', 'VOTERS CARD'), ('DRIVERS LICENCE', 'DRIVERS LICENCE'), ('PASSPORT', 'PASSPORT')], max_length=100)),
                ('id_number', models.IntegerField()),
                ('id_image', models.ImageField(upload_to='pics')),
                ('bvn', models.IntegerField()),
                ('bank_acccount_number', models.IntegerField()),
                ('bank_name', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RegisterUser',
        ),
    ]
