# Generated by Django 4.1.6 on 2023-03-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_profile_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='User',
        ),
    ]
