# Generated by Django 4.1.6 on 2023-03-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_user_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
    ]
